version: '3.7'

services:
  db:
    image: postgres:13.1
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ../database_scripts/Scripts/:/Scripts
    entrypoint: [ "bash", "-c", "/Scripts/run_func_scripts.sh" ]
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./.env

  bot:
    image: shurakostenko/budget_bot:latest
    command: sh -c "python -m main"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

volumes:
  pgdata:
